A

diff --git a/.github/workflows/game-index.yml b/.github/workflows/game-index.yml
--- a/.github/workflows/game-index.yml
+++ b/.github/workflows/game-index.yml
@@ -102,7 +102,7 @@ jobs:
       - name: Publish to PyPI
         if: steps.find_modules.outputs.modules != ''
         env:
-          TWINE_USERNAME: __token__
+          TWINE_USERNAME: delilah
           TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
           TWINE_REPOSITORY_URL: ${{ secrets.PYPI_URL }}
         run: |
@@ -112,6 +112,6 @@ jobs:
           cd src
           for module in ${{ steps.find_modules.outputs.modules }}; do
             echo "Publishing game index module: $module"
-            twine upload "game_index/$module/dist/"*.whl --skip-existing --non-interactive
+            python -m twine upload "game_index/$module/dist/"*.whl --verbose || echo "Failed to upload $module, continuing..."
           done
 
